# Generated by Django 3.0.4 on 2020-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
