# Generated by Django 3.0.4 on 2020-04-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_questions_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='child',
        ),
    ]
