# Generated by Django 3.0.4 on 2020-04-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_remove_questions_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Chat.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='parent',
            field=models.BooleanField(default=True),
        ),
    ]
