# Generated by Django 3.0.4 on 2020-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_auto_20200423_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='parent',
            field=models.BooleanField(default=False),
        ),
    ]
